drop table if exists bert_15_16;
CREATE TABLE bert_15_16 (
	title text,
	category text
);

INSERT INTO bert_15_16 VALUES ('橫跨美加大型輸油管線Keystone因洩漏事故關閉 美油一度漲逾4%','Down');
INSERT INTO bert_15_16 VALUES ('〈美股早盤〉美就業市場降溫 市場押注Fed政策轉向 主要指數開高','Unchanged');
INSERT INTO bert_15_16 VALUES ('華爾街日報：郭台銘一個多月前一封信 讓中國放鬆疫情管制','Down');
INSERT INTO bert_15_16 VALUES ('美國汽油價格比一年前還低 很可能跌破每加侖3美元','Down');
INSERT INTO bert_15_16 VALUES ('鴻海增資印度子公司153億元 傳擴充當地iPhone產能','Unchanged');
INSERT INTO bert_15_16 VALUES ('Adobe：美國網購商品價格大幅下滑 有利Fed','Down');
INSERT INTO bert_15_16 VALUES ('美國上周初領失業金人數升至23萬人 續領者超預期','Unchanged');
INSERT INTO bert_15_16 VALUES ('Disney+廣告版方案正式推出 月費7.99美元','Down');
INSERT INTO bert_15_16 VALUES ('經營權之爭龍邦說重話 泰山也喊提告','Down');
INSERT INTO bert_15_16 VALUES ('Meta將與FTC就VR的未來對簿公堂','Down');
INSERT INTO bert_15_16 VALUES ('CPCA：中國11月乘用車銷量年減近一成 六個月來首降','Unchanged');
INSERT INTO bert_15_16 VALUES ('鉅亨美股雷達：美將公布失業金數據 蘋果公布3項新功能','Unchanged');
INSERT INTO bert_15_16 VALUES ('金管會送大禮 五家期貨商明年可以加發股票股利','Unchanged');
INSERT INTO bert_15_16 VALUES ('避免企業想拿優惠授信「漂綠」 金管會訂出綠色金融投融資標準','Down');
INSERT INTO bert_15_16 VALUES ('傳特斯拉擬縮短上海廠輪班時間 延後新員工報到','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈ESG大趨勢〉首檔連結MSCI巴黎協定氣候指數  柏瑞ESG新基金主打減碳投資','Down');
INSERT INTO bert_15_16 VALUES ('閎康、宜特漲停，設備股誰能跟進','Unchanged');
INSERT INTO bert_15_16 VALUES ('Gamestop轉型承諾跳票 轉而追求短線獲利以滿足投資人','Up');
INSERT INTO bert_15_16 VALUES ('朋億*11月營收飆10.76億元刷新高 明年營運估向上','Unchanged');
INSERT INTO bert_15_16 VALUES ('泰山賣全家股權案 金管會介入調查三大重點','Unchanged');
INSERT INTO bert_15_16 VALUES ('儒鴻11月營收月增2成 累計營收續創同期高','Unchanged');
INSERT INTO bert_15_16 VALUES ('第一金人壽明年元旦資產重分類  淨值預估增加25億元','Down');
INSERT INTO bert_15_16 VALUES ('汎銓11月營收續創同期高 擬斥25億元擴充MA產能','Unchanged');
INSERT INTO bert_15_16 VALUES ('國內首座 中華電打造PCB產業5G專網示範場域','Down');
INSERT INTO bert_15_16 VALUES ('中美晶上半年每股擬配3.2元 喊調降躉購費率衝擊產業','Unchanged');
INSERT INTO bert_15_16 VALUES ('寧德時代與Honda合作深化 達成長期電池供應協議','Up');
INSERT INTO bert_15_16 VALUES ('金字塔頂端客買船不手軟 東哥遊艇全年營收確定將寫新猷','Up');
INSERT INTO bert_15_16 VALUES ('群翊11月營收2.18億元改寫歷史次高 至明年底訂單滿檔','Unchanged');
INSERT INTO bert_15_16 VALUES ('汽車融資需求旺 裕融、和潤11月營收同寫單月新高紀錄','Unchanged');
INSERT INTO bert_15_16 VALUES ('儲能三雄 – 中興電、天宇、耀勝!','Down');
INSERT INTO bert_15_16 VALUES ('兩大利多效應加持 高力11月營收年增61%再創新高','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股11月大漲近2000點  交易戶數逆勢減逾7.6萬戶','Unchanged');
INSERT INTO bert_15_16 VALUES ('晶睿11月營收翻倍續創新猷 前11月年增逾8成','Unchanged');
INSERT INTO bert_15_16 VALUES ('正文、神準11月營收創高 啟碁站穩高檔','Unchanged');
INSERT INTO bert_15_16 VALUES ('龍邦結盟泰山前公司派稱獲53%股權支持 進攻火力全開','Up');
INSERT INTO bert_15_16 VALUES ('內資主導盤面     鴻海MIH大聯盟、 元宇宙全面再攻?','Unchanged');
INSERT INTO bert_15_16 VALUES ('東科-KY元宇宙、非醫療新品明年出貨 獲利優於今年','Unchanged');
INSERT INTO bert_15_16 VALUES ('精剛11月營收1.79億元創新高 看好軍工及航太產業迎復甦','Unchanged');
INSERT INTO bert_15_16 VALUES ('【產業研究報告】賺台積電不如賺台積電概念股-上品','Down');
INSERT INTO bert_15_16 VALUES ('紐約Fed模型暗示 明年美國經濟衰退可能性恐近100%','Down');
INSERT INTO bert_15_16 VALUES ('投資人心懸Fed貨幣政策 關注經濟數據 美債殖利率攀升','Up');
INSERT INTO bert_15_16 VALUES ('和泰車缺車1.5萬台 車用晶片短缺風暴恐延續至明年下半年','Unchanged');
INSERT INTO bert_15_16 VALUES ('旅遊市場復甦 全台無薪假大減近千人 2境外航空停止實施','Up');
INSERT INTO bert_15_16 VALUES ('經濟部通過汎銓投資25億元 深化半導體先進製程研發','Down');
INSERT INTO bert_15_16 VALUES ('聯強11月營收雙減 累計3847億元續創高','Unchanged');
INSERT INTO bert_15_16 VALUES ('加密貨幣熊市衝擊 Coinbase執行長預估今年營收將砍半','Unchanged');
INSERT INTO bert_15_16 VALUES ('和大、宇隆等五家汽車零組件廠 前11月營收均寫同期高','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈元太展望〉永續進程跨大步 成全球首家達成RE20顯示器公司','Up');
INSERT INTO bert_15_16 VALUES ('〈信邦法說〉配合客戶分散生產風險 歐美台三地同步擴產','Up');
INSERT INTO bert_15_16 VALUES ('〈聯發科新晶片亮相〉推天璣8200搶中階市場 終端產品年底前問世','Unchanged');
INSERT INTO bert_15_16 VALUES ('國巨11月營收回溫重返百億元 創同期新高','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈元太展望〉明年營運可望保持成長 電子貨架標籤ESL動能續強','Unchanged');
INSERT INTO bert_15_16 VALUES ('吳敏求認同張忠謀「自由貿易已死」論點 看去台化並非議題','Down');
INSERT INTO bert_15_16 VALUES ('研華、樺漢、光罩、創意、怡利電，十一月營收優選','Up');
INSERT INTO bert_15_16 VALUES ('美股盤前：好市多、博通將發布季報、BMW計畫明年將推11款純電動車!','Up');
INSERT INTO bert_15_16 VALUES ('〈台幣〉與亞幣脫鉤 連3貶收30.685元 續探逾1周低點','Unchanged');
INSERT INTO bert_15_16 VALUES ('台達電前11月營收3500億元 年增23%創同期新高','Unchanged');
INSERT INTO bert_15_16 VALUES ('Q3晶圓代工產值季增6% 本季進入修正期','Down');
INSERT INTO bert_15_16 VALUES ('花旗、美銀預期 美國經濟將在明年下半年陷入衰退','Down');
INSERT INTO bert_15_16 VALUES ('歐盟力拚晶片製造 瞄準台積電、英特爾、三星','Unchanged');
INSERT INTO bert_15_16 VALUES ('美國「台積村」消費商機大 歇腳亭將引進更多品牌搶市','Up');
INSERT INTO bert_15_16 VALUES ('〈信邦法說〉明年營收估維持雙位數成長 未來5年拚翻倍','Unchanged');
INSERT INTO bert_15_16 VALUES ('Appier獲東京證交所批准上市板塊變為Prime 12/15生效','Down');
INSERT INTO bert_15_16 VALUES ('代工廠11月營收兩樣情 緯創累計營收已超越去年全年','Unchanged');
INSERT INTO bert_15_16 VALUES ('基金開箱文》老牌的駿利亨德森平衡策略，簡單ABC投資心法贏面大','Up');
INSERT INTO bert_15_16 VALUES ('〈陸港盤後〉香港可能進一步鬆綁防疫措施 恒生科技指數飆漲逾6%','Unchanged');
INSERT INTO bert_15_16 VALUES ('台企銀前11月稅後純益92.9億元 全年獲利上看百億','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈券商投資展望〉凱基保守看明年 台股高點僅萬五附近','Down');
INSERT INTO bert_15_16 VALUES ('主力多方火種仍在，操作看三大題材個股','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈茂迪展望〉明年躉購費率不升反降 總座：政府未考量四大因素','Down');
INSERT INTO bert_15_16 VALUES ('富采打進低軌衛星國家隊 子公司成關鍵射頻晶片唯一供應商','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈永豐金法說〉近5年總股東報酬144.9% 專業機構投資人持股突破四成','Down');
INSERT INTO bert_15_16 VALUES ('科技廠辦混凝土需求有撐 國產11月營收持穩19億元','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股續疲險守14500點 外資連3砍 三大法人賣超101.92億元','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈永豐金法說〉32萬名股東安啦！明年股利朝配發率6成努力','Up');
INSERT INTO bert_15_16 VALUES ('穩定物價 政院拍板大宗物資降稅延至明年3月底','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈台股盤後〉電子權值領跌  價跌量縮失守月線收在14553點','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈房產〉2022年房市買賣移估回落至32萬棟 6年來首次負成長','Up');
INSERT INTO bert_15_16 VALUES ('胡錫進：讓經濟再次強勁起來 是中國各地民眾共同期待','Down');
INSERT INTO bert_15_16 VALUES ('電金熄火 台股量縮跌76點收14553點 失守月線','Unchanged');
INSERT INTO bert_15_16 VALUES ('【盤中熱點】載板走強昨日遭錯殺？元宇宙個股午盤後走強；IC設計是什麼？','Up');
INSERT INTO bert_15_16 VALUES ('美國科技業勞資新戰線：在家工作vs回辦公室','Up');
INSERT INTO bert_15_16 VALUES ('美國電商、線上旅遊服務業恐放緩 多家股票遭下修評級','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈焦點股〉政策利多加持 光電、風電概念股人氣高','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈房產〉全台百萬戶50年老宅年代來臨 每9戶住宅就有1戶','Down');
INSERT INTO bert_15_16 VALUES ('孫正義悄悄將軟銀持股增至34% 接近可推動私有化水準','Unchanged');
INSERT INTO bert_15_16 VALUES ('謝金河看升息嘆「美好時代過去」：未來投資聚焦這關鍵','Unchanged');
INSERT INTO bert_15_16 VALUES ('港務公司大減港口費用 爭取國際郵輪復航台灣','Up');
INSERT INTO bert_15_16 VALUES ('消息人士：大陸正制訂明年逾5％的經濟成長計畫','Up');
INSERT INTO bert_15_16 VALUES ('「做伙來呷飯」國產米食明星大挑戰正式登場','Up');
INSERT INTO bert_15_16 VALUES ('農委會精選TGA外銷農產品 台北車站辦聖誕市集','Up');
INSERT INTO bert_15_16 VALUES ('烏日啤酒廠風華再現 疫後觀光商機年達6000萬','Up');
INSERT INTO bert_15_16 VALUES ('從投影機跨界無人機 它結盟小7要讓御飯團飛上天','Up');
INSERT INTO bert_15_16 VALUES ('封殺記者惹毛CNN、紐時！馬斯克怕了：我馬上解封帳號','Up');
INSERT INTO bert_15_16 VALUES ('中財辦：大陸今年經濟總量超過人民幣120兆元','Down');
INSERT INTO bert_15_16 VALUES ('《科技》2大OTT平台 2022年度收視排行出爐','Down');
INSERT INTO bert_15_16 VALUES ('《傳產》農曆年將至 超商搶攻年菜商機','Up');
INSERT INTO bert_15_16 VALUES ('《通信網路》電信業唯一！台灣大推5G專案免費看YouTube Premium','Up');
INSERT INTO bert_15_16 VALUES ('《商情》美棉窄幅盤整 鄭棉偏強運行','Unchanged');
INSERT INTO bert_15_16 VALUES ('《電子零件》首家國際品牌酒店 阿里山英迪格明起試營運','Up');
INSERT INTO bert_15_16 VALUES ('防守大戰？摩洛哥、克羅埃西亞交鋒 達人曝運彩投注眉角','Down');
INSERT INTO bert_15_16 VALUES ('想彎道超車？魏哲家：後果恐是保險公司要賠錢','Unchanged');
INSERT INTO bert_15_16 VALUES ('台積電從高中開始搶人才 魏哲家：告訴男同學容易交到女朋友','Unchanged');
INSERT INTO bert_15_16 VALUES ('巴菲特大買台積電 魏哲家：我也借錢加碼投資股票','Unchanged');
INSERT INTO bert_15_16 VALUES ('新創公司佳研智聯 打造工業物聯網的關鍵拼圖','Down');
INSERT INTO bert_15_16 VALUES ('富士康大動作出清紫光持股 公司曝光背後原因','Unchanged');
INSERT INTO bert_15_16 VALUES ('美股資金逃難潮？分析師拋1罕見警告 恐引爆9千億拋售','Unchanged');
INSERT INTO bert_15_16 VALUES ('《半導體》駁去台化、掏空人才 台積電魏哲家提產業2挑戰','Up');
INSERT INTO bert_15_16 VALUES ('巴菲特投資台積電 魏哲家也加碼買 最新動作曝光','Unchanged');
INSERT INTO bert_15_16 VALUES ('半導體去台化議題吵翻 台積電魏哲家重申：門都沒有','Unchanged');
INSERT INTO bert_15_16 VALUES ('不委屈員工！台酒年終獎金　爭取最高額獎金','Up');
INSERT INTO bert_15_16 VALUES ('最猛的還沒來？大陸晶片被踩爛後 美鷹派嗆：只是第一步','Unchanged');
INSERT INTO bert_15_16 VALUES ('《金融股》台灣人壽打造「夢想販賣直播舞台」培訓計畫　','Down');
INSERT INTO bert_15_16 VALUES ('《科技》廢棄漁網變身Galaxy 三星創舉國際比讚','Down');
INSERT INTO bert_15_16 VALUES ('《光電股》焦點股：保勝光學','Up');
INSERT INTO bert_15_16 VALUES ('《其他股》電商市場即將突破兆元 東森將斥資1億元培育3千直播主','Down');
INSERT INTO bert_15_16 VALUES ('拜登又出手毀了「大陸驕傲」 結局曝光：重演華為悲劇','Unchanged');
INSERT INTO bert_15_16 VALUES ('《台北股市》外資放假由內資主導 聚焦「做夢」題材中小型股','Down');
INSERT INTO bert_15_16 VALUES ('《其他電子》鴻海集團出清所有紫光持股','Up');
INSERT INTO bert_15_16 VALUES ('科技戰老是打不贏美國？大陸專家自揭1問題嘆：太弱了','Down');
INSERT INTO bert_15_16 VALUES ('信義房屋選用Google Cloud推動雲端轉型 房地產服務效率升級','Up');
INSERT INTO bert_15_16 VALUES ('雜誌精選》紅心芭樂的2023','Down');
INSERT INTO bert_15_16 VALUES ('大陸晶片反殺美國 拜登可能會輸？專家驚爆2大致命原因','Unchanged');
INSERT INTO bert_15_16 VALUES ('泰山賣全家股票套現80億！龍邦追得回來？雙方心機曝光','Unchanged');
INSERT INTO bert_15_16 VALUES ('雜誌精選》手機與成熟製程 拉回找買點','Up');
INSERT INTO bert_15_16 VALUES ('憂經濟前景 美股連3黑 道瓊下跌281點','Unchanged');
INSERT INTO bert_15_16 VALUES ('台積電AZ廠砸1.2兆 美國滿意了？美專家竟喊：不夠！','Up');
INSERT INTO bert_15_16 VALUES ('日本晶片業停留在40奈米 打算抓緊救命草：美國死敵變盟友','Up');
INSERT INTO bert_15_16 VALUES ('美、中在非洲差距有多大？賴索托這1幕 讓拜登嚇壞了','Down');
INSERT INTO bert_15_16 VALUES ('土地銀行調整牌告利率活用資金 落實ESG理念','Down');
INSERT INTO bert_15_16 VALUES ('加州太陽能發電補助最多砍75％','Down');
INSERT INTO bert_15_16 VALUES ('金融業奧斯卡揭曉 第一金控獲菁業獎「最佳ESG獎」肯定','Down');
INSERT INTO bert_15_16 VALUES ('長線看好 電動車、多元電力趁勢布局','Unchanged');
INSERT INTO bert_15_16 VALUES ('輸銀前十一月稅前盈餘8.5億元 年增13.8％','Down');
INSERT INTO bert_15_16 VALUES ('農金安心GO安全驗證 農特產2023年貨活動開賣','Up');
INSERT INTO bert_15_16 VALUES ('印度今、明年產業營收與盈餘雙位數成長 股市看好','Unchanged');
INSERT INTO bert_15_16 VALUES ('馬斯克不滿專機動向曝光 記者帳號遭禁','Unchanged');
INSERT INTO bert_15_16 VALUES ('臺灣企銀勞資續簽團體協約 提升福利共創永續經營','Down');
INSERT INTO bert_15_16 VALUES ('歐日12月綜合PMI改善','Down');
INSERT INTO bert_15_16 VALUES ('仁寶砸逾9億元、再擴越南產能','Unchanged');
INSERT INTO bert_15_16 VALUES ('蔡崇信據傳減持阿里巴巴','Down');
INSERT INTO bert_15_16 VALUES ('落實普惠金融 彰化銀行「智慧金流服務平台」獲菁業獎肯定','Down');
INSERT INTO bert_15_16 VALUES ('台灣首座金融博物館 「金融探索館」啟用','Down');
INSERT INTO bert_15_16 VALUES ('央行升息 臺銀、一銀、合庫銀、土銀跟進 更貼近足額反映','Up');
INSERT INTO bert_15_16 VALUES ('美股迎四巫日 道瓊跌逾200點 台積電ADR小漲','Unchanged');
INSERT INTO bert_15_16 VALUES ('央行升息半碼 房貸地板價將拉高至1.935％','Unchanged');
INSERT INTO bert_15_16 VALUES ('020028成分股納三陽工業等5檔、刪建大等5檔','Up');
INSERT INTO bert_15_16 VALUES ('00713成分股增亞泥等14檔、刪國泰金等14檔','Down');
INSERT INTO bert_15_16 VALUES ('國票投顧看下周指數區間14200-14800點','Down');
INSERT INTO bert_15_16 VALUES ('台新投顧下周看好PCB、伺服器等八類股','Unchanged');
INSERT INTO bert_15_16 VALUES ('聯電永續經營表現再下一城 CDP評比獲雙A殊榮','Up');
INSERT INTO bert_15_16 VALUES ('中油：永安天然氣接收站海底珊瑚達130種 生態成果媲美保護區','Down');
INSERT INTO bert_15_16 VALUES ('臺灣銀行自12月19日起調整新臺幣存款利率','Down');
INSERT INTO bert_15_16 VALUES ('智崴：2023年將是營收起飛元年 一路延續至2024與2025年','Up');
INSERT INTO bert_15_16 VALUES ('交換禮物收到刮刮樂 她超失望！一刮開全場尖叫狂歡','Down');
INSERT INTO bert_15_16 VALUES ('020007成分股新增達新等9檔、剔除凱美等9檔','Up');
INSERT INTO bert_15_16 VALUES ('00904成分股新增頎邦刪除威盛','Down');
INSERT INTO bert_15_16 VALUES ('00701成分股納聯電等8檔、剔興富發等8檔','Down');
INSERT INTO bert_15_16 VALUES ('00901成分股新增東陽等8檔 另刪裕隆等8檔','Up');
INSERT INTO bert_15_16 VALUES ('00900成分股大汰換 增台積電等20檔刪亞泥等20檔','Down');
INSERT INTO bert_15_16 VALUES ('泰山提告加重毀謗 龍邦劉偉龍：歡迎大伙到法院說清楚！','Down');
INSERT INTO bert_15_16 VALUES ('中磊違反重訊規定 證交所開罰3萬元違約金','Down');
INSERT INTO bert_15_16 VALUES ('國泰萬寶買全家踩產金分離紅線？黃天牧發話了','Down');
INSERT INTO bert_15_16 VALUES ('陽明違反重訊 證交所處以3萬元違約金','Down');
INSERT INTO bert_15_16 VALUES ('經濟部發表南臺灣創新科技研發成果','Down');
INSERT INTO bert_15_16 VALUES ('投標倍數史上次高 2年期存單利率降至1.265％','Up');
INSERT INTO bert_15_16 VALUES ('橫跨美加大型輸油管線Keystone因洩漏事故關閉 美油一度漲逾4%','Down');
INSERT INTO bert_15_16 VALUES ('〈美股早盤〉美就業市場降溫 市場押注Fed政策轉向 主要指數開高','Unchanged');
INSERT INTO bert_15_16 VALUES ('華爾街日報：郭台銘一個多月前一封信 讓中國放鬆疫情管制','Down');
INSERT INTO bert_15_16 VALUES ('美國汽油價格比一年前還低 很可能跌破每加侖3美元','Down');
INSERT INTO bert_15_16 VALUES ('鴻海增資印度子公司153億元 傳擴充當地iPhone產能','Unchanged');
INSERT INTO bert_15_16 VALUES ('Adobe：美國網購商品價格大幅下滑 有利Fed','Down');
INSERT INTO bert_15_16 VALUES ('美國上周初領失業金人數升至23萬人 續領者超預期','Unchanged');
INSERT INTO bert_15_16 VALUES ('Disney+廣告版方案正式推出 月費7.99美元','Down');
INSERT INTO bert_15_16 VALUES ('經營權之爭龍邦說重話 泰山也喊提告','Down');
INSERT INTO bert_15_16 VALUES ('Meta將與FTC就VR的未來對簿公堂','Down');
INSERT INTO bert_15_16 VALUES ('CPCA：中國11月乘用車銷量年減近一成 六個月來首降','Unchanged');
INSERT INTO bert_15_16 VALUES ('鉅亨美股雷達：美將公布失業金數據 蘋果公布3項新功能','Unchanged');
INSERT INTO bert_15_16 VALUES ('金管會送大禮 五家期貨商明年可以加發股票股利','Unchanged');
INSERT INTO bert_15_16 VALUES ('避免企業想拿優惠授信「漂綠」 金管會訂出綠色金融投融資標準','Down');
INSERT INTO bert_15_16 VALUES ('傳特斯拉擬縮短上海廠輪班時間 延後新員工報到','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈ESG大趨勢〉首檔連結MSCI巴黎協定氣候指數  柏瑞ESG新基金主打減碳投資','Down');
INSERT INTO bert_15_16 VALUES ('閎康、宜特漲停，設備股誰能跟進','Unchanged');
INSERT INTO bert_15_16 VALUES ('Gamestop轉型承諾跳票 轉而追求短線獲利以滿足投資人','Up');
INSERT INTO bert_15_16 VALUES ('朋億*11月營收飆10.76億元刷新高 明年營運估向上','Unchanged');
INSERT INTO bert_15_16 VALUES ('泰山賣全家股權案 金管會介入調查三大重點','Unchanged');
INSERT INTO bert_15_16 VALUES ('儒鴻11月營收月增2成 累計營收續創同期高','Unchanged');
INSERT INTO bert_15_16 VALUES ('第一金人壽明年元旦資產重分類  淨值預估增加25億元','Down');
INSERT INTO bert_15_16 VALUES ('汎銓11月營收續創同期高 擬斥25億元擴充MA產能','Unchanged');
INSERT INTO bert_15_16 VALUES ('國內首座 中華電打造PCB產業5G專網示範場域','Down');
INSERT INTO bert_15_16 VALUES ('中美晶上半年每股擬配3.2元 喊調降躉購費率衝擊產業','Unchanged');
INSERT INTO bert_15_16 VALUES ('寧德時代與Honda合作深化 達成長期電池供應協議','Up');
INSERT INTO bert_15_16 VALUES ('金字塔頂端客買船不手軟 東哥遊艇全年營收確定將寫新猷','Up');
INSERT INTO bert_15_16 VALUES ('群翊11月營收2.18億元改寫歷史次高 至明年底訂單滿檔','Unchanged');
INSERT INTO bert_15_16 VALUES ('汽車融資需求旺 裕融、和潤11月營收同寫單月新高紀錄','Unchanged');
INSERT INTO bert_15_16 VALUES ('儲能三雄 – 中興電、天宇、耀勝!','Down');
INSERT INTO bert_15_16 VALUES ('兩大利多效應加持 高力11月營收年增61%再創新高','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股11月大漲近2000點  交易戶數逆勢減逾7.6萬戶','Unchanged');
INSERT INTO bert_15_16 VALUES ('晶睿11月營收翻倍續創新猷 前11月年增逾8成','Unchanged');
INSERT INTO bert_15_16 VALUES ('正文、神準11月營收創高 啟碁站穩高檔','Unchanged');
INSERT INTO bert_15_16 VALUES ('龍邦結盟泰山前公司派稱獲53%股權支持 進攻火力全開','Up');
INSERT INTO bert_15_16 VALUES ('內資主導盤面     鴻海MIH大聯盟、 元宇宙全面再攻?','Unchanged');
INSERT INTO bert_15_16 VALUES ('東科-KY元宇宙、非醫療新品明年出貨 獲利優於今年','Unchanged');
INSERT INTO bert_15_16 VALUES ('精剛11月營收1.79億元創新高 看好軍工及航太產業迎復甦','Unchanged');
INSERT INTO bert_15_16 VALUES ('【產業研究報告】賺台積電不如賺台積電概念股-上品','Down');
INSERT INTO bert_15_16 VALUES ('紐約Fed模型暗示 明年美國經濟衰退可能性恐近100%','Down');
INSERT INTO bert_15_16 VALUES ('投資人心懸Fed貨幣政策 關注經濟數據 美債殖利率攀升','Up');
INSERT INTO bert_15_16 VALUES ('和泰車缺車1.5萬台 車用晶片短缺風暴恐延續至明年下半年','Unchanged');
INSERT INTO bert_15_16 VALUES ('旅遊市場復甦 全台無薪假大減近千人 2境外航空停止實施','Up');
INSERT INTO bert_15_16 VALUES ('經濟部通過汎銓投資25億元 深化半導體先進製程研發','Down');
INSERT INTO bert_15_16 VALUES ('聯強11月營收雙減 累計3847億元續創高','Unchanged');
INSERT INTO bert_15_16 VALUES ('加密貨幣熊市衝擊 Coinbase執行長預估今年營收將砍半','Unchanged');
INSERT INTO bert_15_16 VALUES ('和大、宇隆等五家汽車零組件廠 前11月營收均寫同期高','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈元太展望〉永續進程跨大步 成全球首家達成RE20顯示器公司','Up');
INSERT INTO bert_15_16 VALUES ('〈信邦法說〉配合客戶分散生產風險 歐美台三地同步擴產','Up');
INSERT INTO bert_15_16 VALUES ('〈聯發科新晶片亮相〉推天璣8200搶中階市場 終端產品年底前問世','Unchanged');
INSERT INTO bert_15_16 VALUES ('國巨11月營收回溫重返百億元 創同期新高','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈元太展望〉明年營運可望保持成長 電子貨架標籤ESL動能續強','Unchanged');
INSERT INTO bert_15_16 VALUES ('吳敏求認同張忠謀「自由貿易已死」論點 看去台化並非議題','Down');
INSERT INTO bert_15_16 VALUES ('研華、樺漢、光罩、創意、怡利電，十一月營收優選','Up');
INSERT INTO bert_15_16 VALUES ('美股盤前：好市多、博通將發布季報、BMW計畫明年將推11款純電動車!','Up');
INSERT INTO bert_15_16 VALUES ('〈台幣〉與亞幣脫鉤 連3貶收30.685元 續探逾1周低點','Unchanged');
INSERT INTO bert_15_16 VALUES ('台達電前11月營收3500億元 年增23%創同期新高','Unchanged');
INSERT INTO bert_15_16 VALUES ('Q3晶圓代工產值季增6% 本季進入修正期','Down');
INSERT INTO bert_15_16 VALUES ('花旗、美銀預期 美國經濟將在明年下半年陷入衰退','Down');
INSERT INTO bert_15_16 VALUES ('歐盟力拚晶片製造 瞄準台積電、英特爾、三星','Unchanged');
INSERT INTO bert_15_16 VALUES ('美國「台積村」消費商機大 歇腳亭將引進更多品牌搶市','Up');
INSERT INTO bert_15_16 VALUES ('〈信邦法說〉明年營收估維持雙位數成長 未來5年拚翻倍','Unchanged');
INSERT INTO bert_15_16 VALUES ('Appier獲東京證交所批准上市板塊變為Prime 12/15生效','Down');
INSERT INTO bert_15_16 VALUES ('代工廠11月營收兩樣情 緯創累計營收已超越去年全年','Unchanged');
INSERT INTO bert_15_16 VALUES ('基金開箱文》老牌的駿利亨德森平衡策略，簡單ABC投資心法贏面大','Up');
INSERT INTO bert_15_16 VALUES ('〈陸港盤後〉香港可能進一步鬆綁防疫措施 恒生科技指數飆漲逾6%','Unchanged');
INSERT INTO bert_15_16 VALUES ('台企銀前11月稅後純益92.9億元 全年獲利上看百億','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈券商投資展望〉凱基保守看明年 台股高點僅萬五附近','Down');
INSERT INTO bert_15_16 VALUES ('主力多方火種仍在，操作看三大題材個股','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈茂迪展望〉明年躉購費率不升反降 總座：政府未考量四大因素','Down');
INSERT INTO bert_15_16 VALUES ('富采打進低軌衛星國家隊 子公司成關鍵射頻晶片唯一供應商','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈永豐金法說〉近5年總股東報酬144.9% 專業機構投資人持股突破四成','Down');
INSERT INTO bert_15_16 VALUES ('科技廠辦混凝土需求有撐 國產11月營收持穩19億元','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股續疲險守14500點 外資連3砍 三大法人賣超101.92億元','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈永豐金法說〉32萬名股東安啦！明年股利朝配發率6成努力','Up');
INSERT INTO bert_15_16 VALUES ('穩定物價 政院拍板大宗物資降稅延至明年3月底','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈台股盤後〉電子權值領跌  價跌量縮失守月線收在14553點','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈房產〉2022年房市買賣移估回落至32萬棟 6年來首次負成長','Up');
INSERT INTO bert_15_16 VALUES ('胡錫進：讓經濟再次強勁起來 是中國各地民眾共同期待','Down');
INSERT INTO bert_15_16 VALUES ('電金熄火 台股量縮跌76點收14553點 失守月線','Unchanged');
INSERT INTO bert_15_16 VALUES ('【盤中熱點】載板走強昨日遭錯殺？元宇宙個股午盤後走強；IC設計是什麼？','Up');
INSERT INTO bert_15_16 VALUES ('美國科技業勞資新戰線：在家工作vs回辦公室','Up');
INSERT INTO bert_15_16 VALUES ('美國電商、線上旅遊服務業恐放緩 多家股票遭下修評級','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈焦點股〉政策利多加持 光電、風電概念股人氣高','Unchanged');
INSERT INTO bert_15_16 VALUES ('〈房產〉全台百萬戶50年老宅年代來臨 每9戶住宅就有1戶','Down');
INSERT INTO bert_15_16 VALUES ('孫正義悄悄將軟銀持股增至34% 接近可推動私有化水準','Unchanged');
INSERT INTO bert_15_16 VALUES ('魏哲家帶頭 台積高層砸2.1億買自家股','Unchanged');
INSERT INTO bert_15_16 VALUES ('指數整理，題材股與基期偏低股當道','Down');
INSERT INTO bert_15_16 VALUES ('台股中長期轉多，仍需時間調整','Down');
INSERT INTO bert_15_16 VALUES ('台股險守14,500 後市看中小股','Unchanged');
INSERT INTO bert_15_16 VALUES ('外資大賣3檔金控 友達單日狂掃貨8.7萬張','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股再重挫 黃天牧三字回應','Unchanged');
INSERT INTO bert_15_16 VALUES ('外資、投信落跑 三大法人賣超221.9億元','Unchanged');
INSERT INTO bert_15_16 VALUES ('三大法人提款221億 台股「弱中透強」','Down');
INSERT INTO bert_15_16 VALUES ('半導體雙雄病懨懨 貨櫃三雄當先鋒','Down');
INSERT INTO bert_15_16 VALUES ('魏哲家再買200張自家股 台積電曝原因','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股高息ETF 00919躍績效王','Up');
INSERT INTO bert_15_16 VALUES ('台股修正 長線價值浮現','Unchanged');
INSERT INTO bert_15_16 VALUES ('券商定期定額 11月回籠','Unchanged');
INSERT INTO bert_15_16 VALUES ('雷虎 多頭排列季線有撐','Down');
INSERT INTO bert_15_16 VALUES ('和成 放量漲停挑戰前高','Down');
INSERT INTO bert_15_16 VALUES ('三福化TMAH回收 明年雙位數成長','Up');
INSERT INTO bert_15_16 VALUES ('時碩前11月營收登頂 明年樂觀','Unchanged');
INSERT INTO bert_15_16 VALUES ('中橡Phenix廠停產 衝擊Q4獲利','Down');
INSERT INTO bert_15_16 VALUES ('撼訊 新品利多成交爆量','Down');
INSERT INTO bert_15_16 VALUES ('大宇資 業外進補股價靚','Down');
INSERT INTO bert_15_16 VALUES ('神山神紀錄 連七季當天填息','Down');
INSERT INTO bert_15_16 VALUES ('台股生力軍 好酒沉甕底','Down');
INSERT INTO bert_15_16 VALUES ('IPO今年逆市熱 家數、金額雙高','Up');
INSERT INTO bert_15_16 VALUES ('外資錢進陸海空 近一月狂砍這檔逾17萬張','Unchanged');
INSERT INTO bert_15_16 VALUES ('生技股熄火 軍工、觀光、儲能漲勢整齊','Unchanged');
INSERT INTO bert_15_16 VALUES ('外資轉小賣！台股戰萬五得過3關','Up');
INSERT INTO bert_15_16 VALUES ('台積電貼息!板卡生技聯手漲 台股早盤疲軟','Unchanged');
INSERT INTO bert_15_16 VALUES ('12/15盤前｜國泰蔡家買全家 ATM恐洗牌','Unchanged');
INSERT INTO bert_15_16 VALUES ('外資回頭 高價股吸金 2族群有錢景','Unchanged');
INSERT INTO bert_15_16 VALUES ('玉山投顧：台股戰萬六 聚焦7類機會股','Down');
INSERT INTO bert_15_16 VALUES ('美國通膨回落 台股彈上14,700點','Unchanged');
INSERT INTO bert_15_16 VALUES ('三面俱到 生技類股買點來了','Unchanged');
INSERT INTO bert_15_16 VALUES ('產業穩、收益佳 特別股基金 可望獲資金青睞','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股基金 近月績效紅不讓','Unchanged');
INSERT INTO bert_15_16 VALUES ('台指期 短線震盪整理','Unchanged');
INSERT INTO bert_15_16 VALUES ('台積等3檔除息 大盤縮水23點','Unchanged');
INSERT INTO bert_15_16 VALUES ('倍力掛牌首日 上演蜜月行情','Down');
INSERT INTO bert_15_16 VALUES ('高力 開高走高守穩季線','Down');
INSERT INTO bert_15_16 VALUES ('中興電 多頭排列戰前高','Down');
INSERT INTO bert_15_16 VALUES ('東台今年營運先蹲 明年跳','Unchanged');
INSERT INTO bert_15_16 VALUES ('出貨增溫 永冠Q4轉盈有望','Unchanged');
INSERT INTO bert_15_16 VALUES ('晟銘電 業績登高氣勢壯','Up');
INSERT INTO bert_15_16 VALUES ('投資效益不佳 譁裕處分PBT股權','Down');
INSERT INTO bert_15_16 VALUES ('鉅橡：PCB耗材短空長多 美耐板明年成長動能','Unchanged');
INSERT INTO bert_15_16 VALUES ('訂單在手 亞泰金屬明年不看淡','Unchanged');
INSERT INTO bert_15_16 VALUES ('智原、瑞昱量能大增 股價噴漲','Unchanged');
INSERT INTO bert_15_16 VALUES ('櫃買題材股 法人捧','Up');
INSERT INTO bert_15_16 VALUES ('汽車類股轉強 抗生素題材股籌碼凌亂','Unchanged');
INSERT INTO bert_15_16 VALUES ('台股12月下半場看內資!投信鎖碼股一次看','Up');
INSERT INTO bert_15_16 VALUES ('三大法人大買160億 台股年底行情看它','Unchanged');
INSERT INTO bert_15_16 VALUES ('生技腿軟 多頭點火3族群 台股早盤漲百點','Unchanged');
INSERT INTO bert_15_16 VALUES ('12/14盤前｜2檔伺服器 法人看好明年營運','Unchanged');
INSERT INTO bert_15_16 VALUES ('林啟超：明年上半年買台股 有機會賺2成','Unchanged');
INSERT INTO bert_15_16 VALUES ('00919股利率8.6％吸睛 存股族必備','Up');
INSERT INTO bert_15_16 VALUES ('台股先蹲後跳 低接時機到','Unchanged');
INSERT INTO bert_15_16 VALUES ('低本益比族群受寵 聚焦兩產業','Unchanged');
INSERT INTO bert_15_16 VALUES ('台指期 失守月線支撐','Unchanged');
INSERT INTO bert_15_16 VALUES ('杏一 突破均線多方續攻','Unchanged');
INSERT INTO bert_15_16 VALUES ('中鴻 法人買超價漲量增','Unchanged');
INSERT INTO bert_15_16 VALUES ('旺宏 Flash價格加速回穩','Up');
INSERT INTO bert_15_16 VALUES ('聯電 全年營收有望創高','Unchanged');
INSERT INTO bert_15_16 VALUES ('廖繼弘│月線上下震盪 量縮盤整待變','Unchanged');
INSERT INTO bert_15_16 VALUES ('臺韓集保董座交流 深化合作','Down');
INSERT INTO bert_15_16 VALUES ('倍力14日以每股44.88元掛牌上櫃','Down');
INSERT INTO bert_15_16 VALUES ('淘帝-KY放量漲停 中小型生技股活跳跳','Unchanged');
INSERT INTO bert_15_16 VALUES ('外資賣超102億 台股這族群短多有空間','Unchanged');
INSERT INTO bert_15_16 VALUES ('巨大爆量打開跌停 成交量2020年中來新高','Up');
INSERT INTO bert_15_16 VALUES ('藥荒發作！多頭錢進生技股 專家看好4檔','Unchanged');
INSERT INTO bert_15_16 VALUES ('巨大摜殺跌停 台積電翻紅 台股早盤小漲','Unchanged');
INSERT INTO bert_15_16 VALUES ('美股反彈 挹注台股趨堅架構 聚焦題材股','Up');
INSERT INTO bert_15_16 VALUES ('12/13盤前》AI嵌入崛起 這檔IC轉機有戲','Up');
INSERT INTO bert_15_16 VALUES ('多空觀望 台股爆兩年新低量','Unchanged');
INSERT INTO bert_15_16 VALUES ('興櫃前十強洗牌 雲豹、星宇雙響炮','Up');
INSERT INTO bert_15_16 VALUES ('上市櫃十強前11月營收 衝破15兆','Unchanged');
INSERT INTO bert_15_16 VALUES ('15檔尖兵雙成長 異軍突起','Down');
INSERT INTO bert_15_16 VALUES ('12檔營收步步高 撐盤要角','Down');
INSERT INTO bert_15_16 VALUES ('台股高股息ETF 存愈久股利領愈多','Down');
INSERT INTO bert_15_16 VALUES ('布局台股基金 卡位補漲行情','Unchanged');
INSERT INTO bert_15_16 VALUES ('2022New Futures研討會優秀論文 基於擁擠交易的台股類股輪動策略','Down');
INSERT INTO bert_15_16 VALUES ('台指期 中性區間看待','Down');
INSERT INTO bert_15_16 VALUES ('土洋對作！外資提款官股護盤 10檔逢低敲','Down');
INSERT INTO bert_15_16 VALUES ('裕隆 爆量長紅站回周線','Unchanged');
INSERT INTO bert_15_16 VALUES ('南光 法人力挺短多氣盛','Unchanged');
INSERT INTO bert_15_16 VALUES ('譁裕 基本面佳多方力捧','Down');
INSERT INTO bert_15_16 VALUES ('評價回復行情仍在進行式 優先布局獲利成長族群','Down');
INSERT INTO bert_15_16 VALUES ('無懼台股量能急凍 15檔雙資打卡熱點鍍金','Down');
INSERT INTO bert_15_16 VALUES ('10檔高周轉率股 這檔飆40％人氣超旺','Down');
INSERT INTO bert_15_16 VALUES ('解封＋春節長假 14檔觀光股迎報復性商機','Unchanged');
INSERT INTO bert_15_16 VALUES ('里昂看明年台股高點僅13,500 迄今外資圈最低','Down');
INSERT INTO bert_15_16 VALUES ('台股ETF資產規模飆新高 11月暴衝1,200億','Unchanged');
INSERT INTO bert_15_16 VALUES ('美將禁止魚翅貿易 買賣運輸都是非法','Down');
INSERT INTO bert_15_16 VALUES ('迎擊三星 索尼靠台積電鞏固感測器龍頭地位','Unchanged');
INSERT INTO bert_15_16 VALUES ('歐盟罰單在路上 馬斯克對記者停權剉咧等','Down');
INSERT INTO bert_15_16 VALUES ('魏哲家：地緣政治扭曲半導體市場','Down');
INSERT INTO bert_15_16 VALUES ('美將購300萬桶原油 回補戰略儲油','Unchanged');
INSERT INTO bert_15_16 VALUES ('厭倦內部鬥爭 Meta虛擬實境技術長離職','Down');
INSERT INTO bert_15_16 VALUES ('《大賣空》角色原型摩西警告投資人：遠離特斯拉','Down');
INSERT INTO bert_15_16 VALUES ('2022年全球煤炭消費量創9年新高 推高碳排量','Down');
INSERT INTO bert_15_16 VALUES ('推特前主管曝 150人團隊4小時內幾乎被解散','Unchanged');
INSERT INTO bert_15_16 VALUES ('誠品東南亞首店今開幕 董座吳旻潔：續推動文化交流','Unchanged');
INSERT INTO bert_15_16 VALUES ('停權記者被圍剿 馬斯克軟了：將解封他們帳號','Unchanged');
INSERT INTO bert_15_16 VALUES ('魏哲家示警：過度出口管制 削弱國家間互信','Down');
INSERT INTO bert_15_16 VALUES ('鮑爾：美勞參率低迷跟新冠疫情有關','Unchanged');
INSERT INTO bert_15_16 VALUES ('中國民眾瘋搶藥 海外同款感冒藥貴9倍也搶光','Unchanged');
INSERT INTO bert_15_16 VALUES ('美研機構：中國COVID染疫死亡數 明年恐逾百萬人','Unchanged');
INSERT INTO bert_15_16 VALUES ('主導加密貨幣交易所市場 幣安恐「大到不能倒」','Down');
INSERT INTO bert_15_16 VALUES ('競爭對手帳戶也遭停權 推特恐被反壟斷調查','Unchanged');
INSERT INTO bert_15_16 VALUES ('日月光高雄廠辦選美及耶誕派對 和外籍員工同歡','Up');
INSERT INTO bert_15_16 VALUES ('環洋風電捐贈彰化芳苑33盞路燈 回饋鄉親安全道路','Down');
INSERT INTO bert_15_16 VALUES ('巴菲特買台積電 魏哲家：盼如同Apple股價一路向上','Unchanged');
INSERT INTO bert_15_16 VALUES ('日本發展2奈米想彎道超車？台積電總裁魏哲家：難度很高','Unchanged');
INSERT INTO bert_15_16 VALUES ('特斯拉再拓版圖 擬進駐墨西哥設裝配廠','Unchanged');
INSERT INTO bert_15_16 VALUES ('鴻海出清紫光股份  和碩董座童子賢：歸納為「去中化」有點勉強','Unchanged');
INSERT INTO bert_15_16 VALUES ('通膨數據振奮人心 美前財長：經濟衰退可能更晚發生','Unchanged');
INSERT INTO bert_15_16 VALUES ('台酒：中國僅占營收千分之一 不會做損及國格的事','Down');
INSERT INTO bert_15_16 VALUES ('外媒：高盛年終縮水 將狠砍4000人','Unchanged');
INSERT INTO bert_15_16 VALUES ('馬斯克狂賣股 特斯拉大股東要求換CEO','Unchanged');
INSERT INTO bert_15_16 VALUES ('在美擴產技術會被學走？魏哲家：門都沒有','Down');
INSERT INTO bert_15_16 VALUES ('長江存儲被制裁、鴻海同日出清紫光 「不會是巧合」','Unchanged');
INSERT INTO bert_15_16 VALUES ('買100輛特斯拉「超強卡車」 百事宣布：2023年上路！','Down');
INSERT INTO bert_15_16 VALUES ('美國貿易代表署：延長352項中國進口商品的關稅豁免','Unchanged');
INSERT INTO bert_15_16 VALUES ('WSJ：中國防疫倉促退場 社會不確定性大增','Down');
INSERT INTO bert_15_16 VALUES ('馬雲避禍日本 日經評中國重返毛澤東時代','Down');
INSERT INTO bert_15_16 VALUES ('長江存儲被美列入實體清單 恐退出3D NAND Flash 市場','Down');
INSERT INTO bert_15_16 VALUES ('捉交替？馬斯克正用當初收購價賣推特股票','Unchanged');
INSERT INTO bert_15_16 VALUES ('苗栗公告土地現值平均調幅2％ 頭份這角地蟬聯地王','Unchanged');
INSERT INTO bert_15_16 VALUES ('升息引經濟衰退憂慮 國際油價下跌','Down');
INSERT INTO bert_15_16 VALUES ('黃金漲逾12美元 但週線收黑','Unchanged');
INSERT INTO bert_15_16 VALUES ('出清紫光持股為哪樁？ 鴻海：佈局考量','Down');
INSERT INTO bert_15_16 VALUES ('BBC駐中記者發推  北京一週感染人數破千萬','Down');
INSERT INTO bert_15_16 VALUES ('深夜震撼彈！鴻海宣布全數處分中國紫光持股','Unchanged');
INSERT INTO bert_15_16 VALUES ('飆股幕後》跨足下游針劑業務 台耀吸引外資加碼','Up');
INSERT INTO bert_15_16 VALUES ('貨櫃海運春節前小旺季 不如去年','Down');
INSERT INTO bert_15_16 VALUES ('利率連四升 千萬房貸首年利息多6.19萬','Down');
INSERT INTO bert_15_16 VALUES ('庫存消化慢 封測業估明年Q1觸底','Unchanged');
INSERT INTO bert_15_16 VALUES ('市場派指賤賣全家持股、涉嫌掏空 泰山詹家告龍邦董座誹謗','Down');
INSERT INTO bert_15_16 VALUES ('「快樂檸檬」手搖茶陷苦戰 雅茗-KY擬處分中國事業','Down');
INSERT INTO bert_15_16 VALUES ('避險基金︰中國解封 對美歐經濟非好事','Down');
INSERT INTO bert_15_16 VALUES ('證券行情表、證券表格','Down');
INSERT INTO bert_15_16 VALUES ('遭美股重挫拖累 台股下週持續月線攻防戰','Unchanged');
INSERT INTO bert_15_16 VALUES ('中國紫光持股 鴻海全出清','Down');
INSERT INTO bert_15_16 VALUES ('央行再升息半碼 紓困、學貸新增利息 政府全補貼','Unchanged');
INSERT INTO bert_15_16 VALUES ('取消清零 疫情大爆發 彭博︰中國經濟將出現大動盪','Unchanged');
INSERT INTO bert_15_16 VALUES ('黃志芳︰台積赴美 台灣產業國力延伸','Down');
INSERT INTO bert_15_16 VALUES ('飆股幕後》受惠旅遊市場回溫 雄獅明年Q1營收看俏','Up');
INSERT INTO bert_15_16 VALUES ('憂全球經濟前景 歐股收黑','Unchanged');
INSERT INTO bert_15_16 VALUES ('中央經濟工作會議定新調：挺民企壯大 優化防疫','Down');
INSERT INTO bert_15_16 VALUES ('景氣寒冬 中國影像感測器龍頭高管減薪、春節停工','Unchanged');